package("devkit-a64")
    set_kind("toolchains")
    add_versions("1.0.0", "04220597542a32d40fec13e07f2964685d0cd78e0ada92ec0a6584f90aad37f5")
    set_description("Nintendo Switch aarch64-none-elf toolchain")
    set_homepage("https://github.com/HelloEngine/devkit-a64")
    add_urls("https://github.com/HelloEngine/devkit-a64/releases/download/$(version)/devkit-a64.zip")

    on_load(function(package)
        package:addenv("DEVKITA64", package:installdir())
    end)

    on_install("cross@windows", "cross@msys", function(package)
        os.cp("aarch64-none-elf", package:installdir())
        os.cp("bin", package:installdir())
        os.cp("include", package:installdir())
        os.cp("lib", package:installdir())
        os.cp("libexec", package:installdir())
        os.cp("share", package:installdir())
        os.cp("xmake.lua", package:installdir() .. "/xmake.lua")
    end)

    on_test(function(package)
        assert(os.exists(package:installdir() .. "/bin/aarch64-none-elf-c++.exe"))
    end)
package_end()