package("devkit-a64-gdb")
    add_versions("1.0.0", "7c09d4c518cab53d8efc108c3c9b7fa1ea3fe58cb53bb1d0a5c385d6a2d6731b")
    set_description("Nintendo Switch aarch64-none-elf gdb")
    set_homepage("https://github.com/HelloEngine/devkit-a64-gdb")
    add_urls("https://github.com/HelloEngine/devkit-a64-gdb/releases/download/$(version)/devkit-a64-gdb.zip")

    on_load(function(package)
        package:addenv("DEVKITA64_GDB", package:installdir())
    end)

    on_install("cross@msys","cross@windows", function(package)
        os.cp("bin", package:installdir())
        os.cp("include", package:installdir())
        os.cp("lib", package:installdir())
        os.cp("share", package:installdir())
        os.cp("xmake.lua", package:installdir() .. "/xmake.lua")
    end)

    on_test(function(package)
        assert(os.exists(package:installdir() .. "/bin/aarch64-none-elf-gdb.exe"))
    end)
package_end()