package("switch-glad")
    set_description("Switch port of an autogenerated OpenGL 4.3 loader")
    set_homepage("https://github.com/HelloEngine/switch-glad")

    add_versions("1.0.0", "1000f80fcc559e0ec4ce3ef808620fd0266ef519a73ace72ffe1c18c36943b90")
    add_urls("https://github.com/HelloEngine/switch-glad/releases/download/$(version)/switch-glad.zip")

    on_install("cross@windows", "cross@msys", function(package)
        os.cp("include", package:installdir())
        os.cp("lib", package:installdir())
        os.cp("xmake.lua", package:installdir() .. "/xmake.lua")
    end)
package_end()